// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// parseLineProfileRefs
List parseLineProfileRefs(std::string input);
RcppExport SEXP lineprof_parseLineProfileRefs(SEXP inputSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        std::string input = Rcpp::as<std::string >(inputSEXP);
        List __result = parseLineProfileRefs(input);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
