# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

contains <- function(haystack, needle) {
    .Call('lineprof_contains', PACKAGE = 'lineprof', haystack, needle)
}

firstTRUE <- function(x) {
    .Call('lineprof_firstTRUE', PACKAGE = 'lineprof', x)
}

parseLineProfileRefs <- function(input) {
    .Call('lineprof_parseLineProfileRefs', PACKAGE = 'lineprof', input)
}

#' Pause execution
#'
#' This is similar to \code{\link{Sys.sleep}} but is captured during
#' profiling, making it useful when generating simple examples.
#'
#' @export
#' @param sec Number of seconds to pause (millsecond resolution).
pause <- function(sec) {
    invisible(.Call('lineprof_pause', PACKAGE = 'lineprof', sec))
}

